### ISSUE TITLE
Complete the translation of the documentation into Russian

### ISSUE THREAD

**Issue by ezekeli** [JuliaLang/www_old.julialang.org#539]
Hi, my dear friends!
I want to complete the translation of the julialang.org into Russian.
What resources should be corrected for localization at least the main page?

**Comment by ChrisRackauckas** [comment]
@Ismael-VC

**Comment by Ismael-VC** [comment]
@ezekeli I've added you as a reviewer in the translation team.

In order to localize the main page, you have to translate the missing strings and **also** approve them as reviewed (only translating them will not make them show up at julialang.org!).

Please feel free to ping me back once you have translated a portion of them so I can push your changes to production.

Cheers.

**Comment by ViralBShah** [comment]
Consider adding to the `Community` section of the new website.
