### ISSUE TITLE
Too many things in the navigation bar on top

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/www_old.julialang.org#674]
There are far too many things on the top bar. I propose removing several:

1. I think we recently introduced `ecosystems`, but I don't think it should be there. I think it should be referred to on the `community` page, since these ecosystems are sort of micro-communities within the larger community.

2. Let's combine `teaching` and `learning`. It can be a list of learning resources, followed by a list of classes it is taught in. Perhaps for the list of classes, we can adopt the publications format for submission. Rather than have a comprehensive list of all books and all tutorials there - I think we should only have a few, with a link to the full list.

3. Remove GSoC for now and introduce it when we are accepted again.

4. `blog` should always be last, so that it is always in that place visibily.

Some of this is going to be subjective, but I think it is time to clean up the sprawl.

**Comment by ChrisRackauckas** [comment]
One thing to note is that I have been pointing students to the GSoC page when I introduce them to Julia. Maybe it is early but it is a nice thing to show.

**Comment by ViralBShah** [comment]
I am not advocating removing the gsoc pages - just the link in the navigation bar.

**Comment by MikeInnes** [comment]
Having submenus would help with this (easy to do with bootstrap).

**Comment by crstnbr** [comment]
I think this is really necessary - We've been looking at this ugly line break for long enough :)

On a general note, what I dislike about the current navigation is that it seems (with some exceptions) kind of object focused: here is a blog, here are some downloads, here are some publications, here are the docs, and so on. I prefer some more user/visitor action focused navigation in the spirit of: Install, Contribute, Learn, and so on. Of course, in reality it is most likely going to be a mixture but the latter approach seems to be the one that should be preferred if possible. Examples in this direction would be maybe [Rust](http://www.rust-lang.org) and [Swift](https://developer.apple.com/swift/).

I'd love see this thread not only lead to fewer navigation items but to such a change of style.

**Comment by crstnbr** [comment]
However, let me ignore my last general comment for a second and just propose some changes within the current style.

In my opinion `source` (just a link to the github repo) and `downloads` should be combined in some way.
- The github repo is already - although without a link - the first thing that is mentioned on the downloads page.
- If I want to download the Julia source to build Julia myself I might click source on the main page instead of going to downloads -> source. I assume most people wouldn't be interested in cloning the master branch of the repo but downloading a tar.gz of the latest stable release.

I'm not sure if `publications` deserves to be in the navigation. Seems to me that it's too irrelevant for most of the general audience. (Of course I think it should be on the webpage but maybe not in the navigation)

Also, I'm not sure if `GSoC` - which btw breaks the general lowercase style - and even `juliacon` belongs in the navigation. I haven't clicked on `GSoC` once in the last year. And not only does there exist a separate website for JuliaCon but it's also only once a year, which makes this link almost irrelevant for let's say half a year, every year. However, I don't have very strong feelings here. But I guess a notification/banner of some kind would be more apropriate for indicating a conference than a permanent navigation link.

Those are my two cents and I'm looking forward to a discussion which will make the Julia webpage more transparent and inviting.

**Comment by ViralBShah** [comment]
There is some work in progress on a new design for the website. Hopefully that will address many of these comments. Will post here as soon as ready.

**Comment by crstnbr** [comment]
Great to hear. Looking forward to get a glimpse.
