### ISSUE TITLE
Add more info about donating

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/www_old.julialang.org#791]
I think it would be very useful to know where the money goes, and what it is used for. I think people (at least I) would be much more willing to donate if they had this information.

**Comment by ararslan** [comment]
@ViralBShah, @Dr-G

**Comment by ViralBShah** [comment]
Good point. The money goes to NumFocus and pretty much goes towards maintaining the community infrastructure, which costs about $1500/month (Travis, Appveyor, Discourse, AWS, Digital Ocean, GMail for julialang.org, and maybe some other small things). Currently, we try to make it so that proceeds from JuliaCon can cover the conference expenses, travel scholarships and a whole year of operations.

Of course, if there was more money, then we can think of doing more things. Also open to other ideas on what we should do.

**Comment by Dr-G** [comment]
I generally explain that donations "help our projects pay for developer time, professional services, travel, workshops, and a variety of other needs."

**Comment by ViralBShah** [comment]
I say we go with @Dr-G 's suggested phrasing.

**Comment by ViralBShah** [comment]
Anyone want to add Dr-G's suggested phrase below the Donate button?
